fireos=4
adm=0.2
amazon-remoteviews=0.1
backup=1.0
cms=3.11
contentsupportmanager=0.1
contextcardsplatform=0.1
csf=3.2
dcpcontracts=0.1
dcpframework=0.1
dcpsettings=0.1
directtexture=0.1
downloadmanager=0.1;3.0
enhancedcamera-api=1.0
enterprisewhitelistedurlmanager=0.1
firefly-api=0.1
firefly-beta-api=0.1
fireos-managers-core=3.2
fireos-managers-core-deprecated=3.0
fireos-utils-core=3.0
fireos-utils-core-deprecated=3.1
home-internal=0.1
i18n-utilities=0.1
icu4j=3.0
idme=0.1
jackson=0.1
mapclientlib=3.0
maps=0.1
messaging=0.1
metrics=3.1
retaildemo=0.1
sics=0.1
tcomm=0.2
trapz=0.1
unifiedsearch=0.1
whispersync=0.1
